# Generated by Django 5.2.17 on 2026-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Shown on the public Courses/Internships pages when true.'),
        ),
    ]
