# Generated by Django 5.2.17 on 2026-09-09 05:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('Academic Project Enquiry', 'BCA / MCA Project Enquiry'), ('Course Admission', 'Course / Training Admission'), ('Internship Application', 'IT Internship Application'), ('College Partnership', 'College / Institution Workshop'), ('General Query', 'Other General Query')], default='General Query', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New / Unread'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes visible only to ERP staff.')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'db_table': 'website_contact_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistrationInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('BCA (Bachelor of Computer Applications)', 'BCA'), ('MCA (Master of Computer Applications)', 'MCA'), ('B.E. / B.Tech (CS / IT / ECE)', 'BE / BTech'), ('BSc Computer Science', 'BSc CS'), ('Diploma in Computer Science', 'Diploma CS / IT'), ('Other Degree Stream', 'Other')], default='BCA (Bachelor of Computer Applications)', max_length=100)),
                ('program', models.CharField(choices=[('Academic Project Guidance', 'BCA / MCA Final Year Project'), ('Full Stack Web Development (MERN)', 'Full Stack Web Development (MERN)'), ('Python & Data Science Course', 'Python & Data Analytics'), ('Software Internship Track', 'IT / Software Internship'), ('Java Enterprise Track', 'Java Enterprise Engineering'), ('Flutter Mobile App Track', 'Mobile App Development')], default='Academic Project Guidance', max_length=100)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Application'), ('CONTACTED', 'Contacted by Coordinator'), ('ENROLLED', 'Converted to Enrollment'), ('REJECTED', 'Rejected / Ineligible')], db_index=True, default='NEW', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes visible only to ERP staff.')),
            ],
            options={
                'verbose_name': 'Student Registration Inquiry',
                'verbose_name_plural': 'Student Registration Inquiries',
                'db_table': 'website_student_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
