# Generated by Django 5.2.17 on 2026-09-20 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('partner', 'Partner College / Training Association'), ('recognition', 'Official Recognition / Certification'), ('about', 'About Gnana Computech Solutions'), ('owner', 'Owner / Leadership'), ('impact_stat', 'Our Impact in Numbers'), ('event', 'Event / Workshop'), ('service', 'Technology Service'), ('internship', 'Internship Program'), ('testimonial', 'Student & Partner Story')], db_index=True, max_length=20)),
                ('title', models.CharField(help_text="Name / heading (e.g. college name, owner's name, stat label).", max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. designation, role, badge, program type.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('link_url', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_start', models.DateTimeField(blank=True, help_text='Event section: start date & time.', null=True)),
                ('event_end', models.DateTimeField(blank=True, help_text='Event section: end date & time (optional).', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower shows first within its section.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Unpublished items are hidden from the public site but stay editable.')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Section-specific extras, e.g. {"features": [...], "technologies": [...], "rating": 5}.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_content_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'db_table': 'website_site_content',
                'ordering': ['section', 'display_order', '-created_at'],
            },
        ),
    ]
